/**
 * Controlled PoC pilot configuration (Phase 11, task 11.1).
 *
 * The declarative dataset the idempotent pilot import writes into the store:
 * the VSDD programme, its five streams and all eight teams, one two-week pilot
 * sprint (whose Week 1 / Week 2 checkpoints are generated by the hierarchy-admin
 * `create-sprint` per R2.1, with Week 1 made CURRENT per R2.2), and the pilot
 * accounts / roles / assignments that let all eight teams report and Leadership
 * roll up (R1a, R17, pilot success criteria).
 *
 * This is CONFIG, not code: the hierarchy mirrors the vendor-neutral reference
 * seed (`referenceData.ts`) exactly — same stable ids and names — so the import
 * reconciles cleanly against a store that was already reference-seeded on
 * startup (no duplicates, no silent overwrite). The programme, streams and teams
 * are re-exported from the single source of truth rather than re-declared here.
 *
 * Passwords are NEVER stored here. The import receives a single default password
 * out-of-band (an env var read by the CLI); newly-created accounts get that
 * password (to be changed on first login) and re-runs never touch credentials.
 */
import type { Role } from '../domain/identity.js';
import {
  PROGRAMME,
  PROGRAMME_ID,
  STREAMS,
  TEAMS,
} from './referenceData.js';

export { PROGRAMME, PROGRAMME_ID, STREAMS, TEAMS };

/** A single two-week pilot sprint. Its two weekly checkpoints (R2.1) are
 * derived by the hierarchy-admin `createSprint` as `${id}-W1` / `${id}-W2`. */
export interface PilotSprintConfig {
  id: string;
  label: string;
  /** ISO date (UTC). */
  startDate: string;
  /** ISO date (UTC) — two weeks after the start. */
  endDate: string;
}

export const PILOT_SPRINT: PilotSprintConfig = {
  id: 'pilot-sprint-1',
  label: 'Pilot Sprint 1',
  startDate: '2026-01-05',
  endDate: '2026-01-16',
};

/** Deterministic checkpoint ids the hierarchy-admin `createSprint` produces. */
export const PILOT_CHECKPOINT_W1_ID = `${PILOT_SPRINT.id}-W1`;
export const PILOT_CHECKPOINT_W2_ID = `${PILOT_SPRINT.id}-W2`;

/**
 * A pilot account definition. Keyed for idempotency by its lowercased `email`
 * (the natural unique key); `id` is a STABLE deterministic account id so
 * re-runs match the existing record instead of creating a duplicate.
 */
export interface PilotAccountConfig {
  id: string;
  email: string;
  displayName: string;
  roles: Role[];
  /** Teams the account may act on (Contributor / Team Lead scope). */
  teamIds: string[];
}

/**
 * The first pilot Admin. Created via the idempotent first-admin bootstrap so
 * the approval workflow has an administrator; that admin is then the actor for
 * every subsequent hierarchy / assignment write in the import.
 */
export const PILOT_ADMIN: PilotAccountConfig = {
  id: 'pilot-admin',
  email: 'pilot-admin@vsdd.example',
  displayName: 'Pilot Admin',
  roles: ['ADMIN'],
  teamIds: [],
};

/**
 * The pilot roll-up roles (programme-scoped, no team assignment): one
 * Leadership viewer to consume the complete roll-up and one read-only Auditor.
 */
export const PILOT_PROGRAMME_ACCOUNTS: PilotAccountConfig[] = [
  {
    id: 'pilot-leadership',
    email: 'pilot-leadership@vsdd.example',
    displayName: 'Pilot Leadership',
    roles: ['LEADERSHIP'],
    teamIds: [],
  },
  {
    id: 'pilot-auditor',
    email: 'pilot-auditor@vsdd.example',
    displayName: 'Pilot Auditor',
    roles: ['AUDITOR'],
    teamIds: [],
  },
];

/**
 * One Team Lead and one Contributor per team, so all eight teams can report
 * both weeks (pilot success criteria). Derived from the reference teams so the
 * set stays in lock-step with the hierarchy.
 */
export const PILOT_TEAM_ACCOUNTS: PilotAccountConfig[] = TEAMS.flatMap((team) => [
  {
    id: `pilot-lead-${team.id}`,
    email: `lead.${team.id}@vsdd.example`,
    displayName: `${team.name} — Team Lead`,
    roles: ['TEAM_LEAD'] as Role[],
    teamIds: [team.id],
  },
  {
    id: `pilot-contrib-${team.id}`,
    email: `contrib.${team.id}@vsdd.example`,
    displayName: `${team.name} — Contributor`,
    roles: ['CONTRIBUTOR'] as Role[],
    teamIds: [team.id],
  },
]);

/**
 * Every non-admin pilot account (the programme roll-up roles plus the per-team
 * leads and contributors). The Admin is bootstrapped separately.
 */
export const PILOT_ACCOUNTS: PilotAccountConfig[] = [
  ...PILOT_PROGRAMME_ACCOUNTS,
  ...PILOT_TEAM_ACCOUNTS,
];
